### PR TITLE
Improve validation error message logging

### PR DESCRIPTION
**Pull request by FanDjango**

### CODE REVIEW

**Comment by robinrodricks** [comment]
Looks good, thanks!

Lmk when we should release.

**Comment by FanDjango** [comment]
I just did, LOL, it was a preparation for GnuTLS 3.8.0

**Comment by robinrodricks** [comment]
Oh sorry, I got confused. I thought this was the main project. Good job!

**Comment by FanDjango** [comment]
You're the best, Robin, all is good. I felt it is sensible to segregate these changes from another for possible revert-ability.

In the end, there might also be a small change in FluentFTP itself to report "better" on authentication failures - it sort of keeps the inner exception from surfacing. But that is not urgent at all right now.

**Pull request merged**
